apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-simulator
  template:
    metadata:
      labels:
        app: sensor-simulator
    spec:
      containers:
        - name: sensor-simulator
          image: ghcr.io/zgulce0/tactical-edge-sensor-simulator:latest
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "admin"
            - name: RABBITMQ_PASS
              value: "admin123"
            - name: QUEUE_NAME
              value: "sensor_data"
            - name: SEND_INTERVAL
              value: "2"
            - name: DEVICE_ID
              value: "sensor-001"